[package]
name = "zorn-core"
authors = ["Viktor Kleen <viktor@kleen.org>"]
version = "0.1.0"
edition = "2021"

[dependencies]
x25519-dalek = "1.2.0"
zeroize = { version = "1.3", features = ["zeroize_derive"] }
rand = "0.8.5"
subtle = "2.4.1"
